language: python

python:
    - "2.7"

env:
    - secure: "hF7dvNL5EMY58vPPkak0+bkRbRAkN+AedXFoSVjqMIO9gCvO65YgEZcED1VtBLZkFiKxM8wx+H0PcEV07vHSBidIB0KI/s+k4DcuhjHlN6/XZ4ktVKQtXHj5wWFsmiMPqUDwm2DLk7LEFEw6kluudtcurJUN0CdhoApA+sbtbeopZPT/292DT9WIHN9GTrc/zy1lWK5EuBa8Pbk38SOvY+m3bGwhwXr76WxkHg4o2Ju71LtNUeXPWxo5W15KKf9+T8R0hN4NjKGXfdaU3y68nuL4nUO7EZLU0i9m5a3SuadXcpnB6TYKEK0fmX2Nr9Frt0VSN1EtJvtaflvs/QWEGnLTjhhTuIzmgND1i6/pgf7fF1RKl6vCp19aQRjG9aHQJyrDncCSDTfeewmXwL7GEixMB7AVYaXj9ImMn3T40yHf4JJtNaC02uwQ3AEbC0Syc5ak69wCQOPFLINQ9R7Q3WMaH+x2BUSK/3Bs6d+G75lqksdYyPRrhEtdprd+NEyvlTIkke9egR94YG9wt4evgWbxRDjlXAJo2J89UsgLAMKWDUKwvNsyN20lsBn7Wzlq+PIJ1fMPZIl/bK1GI/7USCiH325IPfIbCazHhuPT0UAVqQs+kYLtW6IQOdPUofN0AIhId/l8rmqML9c8/gzd9W9bg4L+65BKTe3MGyXv7SE="

before_install:
    - sudo apt-get update

install:
    - sudo pip install pelican
    - sudo pip install markdown
    - sudo pip install s3cmd

script:
    - pelican content

after_success:
    - s3cmd sync output/ s3://www.wogong.net --acl-public --delete-removed --guess-mime-type --access_key=$ACCESS_KEY --secret_key=$SECRET_KEY
