title: wogong
baseurl: ""
production_url: http://www.wogong.net
permalink: /blog/:title

timezone: Asia/Shanghai
markdown: rdiscount

author:
    name: wogong
    email: i@wogong.net


collections:
    wiki:
        output: true
    i:
        output: true
    doc:
        output: false
    read:
        output: true


# front-matter default
defaults:
    -
#        scope:
#            path: "" # empty string for all files
#        values:
#            layout: "post"
#    -
        scope:
            path: "blog"
            type: "post" #page, post or draft
        values:
            layout: "post" # overrides previous default layout
            author: "wogong"
            category: "blog"
