title: wogong
baseurl: ""
production_url: https://wogong.github.io
permalink: /blog/:title

timezone: Asia/Shanghai
#markdown: rdiscount

author:
    name: wogong
    email: i@wogong.net

collections:
    wiki:
        output: true
    life:
        output: true

# front-matter default
defaults:
    -
#        scope:
#            path: "" # empty string for all files
#        values:
#            layout: "post"
#    -
        scope:
            path: "post"
            type: "post" #page, post or draft
        values:
            layout: "post" # overrides previous default layout
            author: "wogong"
            category: "blog"
        scope:
            path: "wiki"
            type: "post" #page, post or draft
        values:
            layout: "wiki" # overrides previous default layout
            author: "wogong"
            category: "wiki"
