title: wogong
baseurl: ""
production_url: https://wogong.github.io
permalink: /blog/:title

timezone: Asia/Shanghai
#markdown: rdiscount

author:
    name: wogong
    email: hi@wogong.net

collections:
    wiki:
        output: true

# front-matter default
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default" # overrides previous default layout
    -
        scope:
            path: ""
            type: "wiki" #page, post or draft
        values:
            layout: "wiki" # overrides previous default layout
            author: "Cheng Zhen"
